"""Centralized runtime constants for the Shimeji agent."""

from __future__ import annotations

DEFAULT_FLASH_MODEL = "gemini-2.5-flash"
DEFAULT_PRO_MODEL = "gemini-2.5-pro"
DEFAULT_PERSONALITY = "playful_helper"

DEFAULT_PROACTIVE_INTERVAL_SECONDS = 45
DEFAULT_REACTION_INTERVAL_SECONDS = 10

DEFAULT_LISTEN_HOST = "127.0.0.1"
DEFAULT_LISTEN_PORT = 8770
DEFAULT_ANCHOR_POLL_SECONDS = 0.25

DEFAULT_BUBBLE_REPOSITION_INTERVAL_MS = 100
DEFAULT_REQUEST_TIMEOUT_SECONDS = 2.5

DEFAULT_STARTUP_DELAY_SECONDS = 1.0
MIN_STARTUP_DELAY_SECONDS = 0.1

DEFAULT_MEMORY_CLEANUP_INTERVAL_SECONDS = 3600
DEFAULT_VISION_ANALYSIS_INTERVAL_SECONDS = 45
